wipe = true
output   = "./../../../api/models"
add-soft-deletes    = true
no-back-referencing = true
no-hooks = true
no-tests = true

[mysql]
  dbname  = "nchronus"
  host    = "localhost"
  user    = "root"
  pass    = "adminimda"
  sslmode = "false"
